const navButtons = document.querySelectorAll("[data-view-btn]");
const views = document.querySelectorAll("[data-view]");
const langButtons = document.querySelectorAll(".lang-btn");
const toast = document.getElementById("toast");
const editorModal = document.getElementById("editorModal");
const questionList = document.getElementById("questionList");

const tagFilter = document.getElementById("tagFilter");
const classFilter = document.getElementById("classFilter");
const typeFilter = document.getElementById("typeFilter");

const openEditorBtn = document.getElementById("openEditorBtn");
const closeEditorBtn = document.getElementById("closeEditorBtn");
const addQuestionBtn = document.getElementById("addQuestionBtn");
const runGenerationBtn = document.getElementById("runGenerationBtn");
const progressBar = document.getElementById("progressBar");
const progressText = document.getElementById("progressText");
const notifyBtn = document.getElementById("notifyBtn");

const questionTypeSelect = document.getElementById("questionTypeSelect");
const addOptionRu = document.getElementById("addOptionRu");
const addOptionKk = document.getElementById("addOptionKk");
const optionsRu = document.getElementById("optionsRu");
const optionsKk = document.getElementById("optionsKk");

const questionRu = document.getElementById("questionRu");
const questionKk = document.getElementById("questionKk");
const aiExplanation = document.getElementById("aiExplanation");
const copyToLectureBtn = document.getElementById("copyToLectureBtn");
const lectureDraft = document.getElementById("lectureDraft");

const approveFromModalBtn = document.getElementById("approveFromModalBtn");
const rejectFromModalBtn = document.getElementById("rejectFromModalBtn");

let generationTimer = null;

function notify(message) {
  toast.textContent = message;
  toast.classList.remove("hidden");
  window.setTimeout(() => toast.classList.add("hidden"), 1800);
}

function setActiveView(viewName) {
  views.forEach((view) => {
    const isTarget = view.dataset.view === viewName;
    view.classList.toggle("view-hidden", !isTarget);
  });
}

function setActiveNav(button) {
  navButtons.forEach((btn) => {
    btn.className =
      "nav-btn flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 py-2 text-left text-sm font-medium text-slate-700 hover:bg-slate-50";
  });
  button.className =
    "nav-btn flex items-center gap-2 rounded-xl border border-indigo-100 bg-indigo-50 px-3 py-2 text-left text-sm font-medium text-indigo-700";
}

function normalizeType(typeValue) {
  return typeValue === "single" ? "Один ответ" : "Множественный";
}

function makeStatusBadge(status) {
  if (status === "published") {
    return '<span class="rounded-full bg-emerald-100 px-2.5 py-1 text-xs font-semibold text-emerald-700">Published</span>';
  }
  if (status === "review") {
    return '<span class="rounded-full bg-amber-100 px-2.5 py-1 text-xs font-semibold text-amber-700">Under Review</span>';
  }
  return '<span class="rounded-full bg-purple-100 px-2.5 py-1 text-xs font-semibold text-purple-700">Generated by AI</span>';
}

function updateCardStatus(card, status) {
  card.dataset.status = status;
  const statusBadge = card.querySelector(".status-badge-host");
  statusBadge.innerHTML = makeStatusBadge(status);
}

function applyFilters() {
  const tagValue = tagFilter.value;
  const classValue = classFilter.value;
  const typeValue = typeFilter.value;
  const cards = questionList.querySelectorAll(".question-card");

  cards.forEach((card) => {
    const matchTag = tagValue === "all" || card.dataset.tag === tagValue;
    const matchClass = classValue === "all" || card.dataset.class === classValue;
    const matchType = typeValue === "all" || card.dataset.type === typeValue;
    card.classList.toggle("hidden", !(matchTag && matchClass && matchType));
  });
}

function openEditor(questionRuText, questionKkText) {
  if (questionRuText) {
    questionRu.value = questionRuText;
  }
  if (questionKkText) {
    questionKk.value = questionKkText;
  }
  editorModal.classList.remove("hidden");
  editorModal.classList.add("flex");
}

function closeEditor() {
  editorModal.classList.add("hidden");
  editorModal.classList.remove("flex");
}

function createOptionRow(languageCode, inputType) {
  const wrapper = document.createElement("label");
  wrapper.className = "option-row flex items-center gap-2 rounded-xl border border-slate-200 px-3 py-2";
  wrapper.innerHTML = `
    <input type="${inputType}" name="correct${languageCode}">
    <input class="w-full text-sm outline-none" value="Новый вариант">
    <button type="button" class="remove-option rounded-lg border border-slate-200 px-2 py-1 text-xs text-slate-600 hover:bg-slate-50">Удалить</button>
  `;
  return wrapper;
}

function ensureRemovers(container) {
  const rows = container.querySelectorAll("label");
  rows.forEach((row) => {
    if (!row.querySelector(".remove-option")) {
      const btn = document.createElement("button");
      btn.type = "button";
      btn.className = "remove-option rounded-lg border border-slate-200 px-2 py-1 text-xs text-slate-600 hover:bg-slate-50";
      btn.textContent = "Удалить";
      row.appendChild(btn);
    }
  });
}

function addDemoQuestion(source = "manual") {
  const createdAt = new Date().toLocaleTimeString("ru-RU", { hour: "2-digit", minute: "2-digit" });
  const card = document.createElement("article");
  card.dataset.status = "generated";
  card.dataset.tag = "МОДО";
  card.dataset.class = "8";
  card.dataset.type = "single";
  card.className = "question-card rounded-2xl border border-slate-200 bg-white p-4 shadow-sm";
  card.innerHTML = `
    <div class="flex flex-wrap items-start justify-between gap-3">
      <div class="space-y-2">
        <div class="flex flex-wrap items-center gap-2">
          <span class="status-badge-host">${makeStatusBadge("generated")}</span>
          <span class="rounded-full bg-slate-100 px-2.5 py-1 text-xs text-slate-600">8 класс</span>
          <span class="rounded-full bg-slate-100 px-2.5 py-1 text-xs text-slate-600">МОДО</span>
          <span class="rounded-full bg-slate-100 px-2.5 py-1 text-xs text-slate-600">${normalizeType("single")}</span>
        </div>
        <h3 class="text-sm font-semibold text-slate-900">RU: Пример новой задачи (${source}, ${createdAt}). Выберите правильный ответ.</h3>
        <p class="text-sm text-slate-600">KK: Жаңа тапсырма үлгісі (${source}, ${createdAt}). Дұрыс жауапты таңдаңыз.</p>
      </div>
      <button class="edit-btn rounded-xl border border-slate-200 px-3 py-2 text-xs font-semibold text-slate-700 hover:bg-slate-50">Редактировать</button>
    </div>
    <div class="mt-4 flex flex-wrap gap-2">
      <button class="approve-btn rounded-xl bg-emerald-500 px-4 py-2.5 text-sm font-semibold text-white hover:bg-emerald-600">Approve</button>
      <button class="reject-btn rounded-xl bg-amber-500 px-4 py-2.5 text-sm font-semibold text-white hover:bg-amber-600">Reject</button>
    </div>
  `;
  questionList.prepend(card);
  applyFilters();
}

function switchLanguage(lang) {
  langButtons.forEach((btn) => {
    const active = btn.dataset.lang === lang;
    btn.classList.toggle("bg-indigo-600", active);
    btn.classList.toggle("text-white", active);
    btn.classList.toggle("text-slate-600", !active);
  });
  document.documentElement.lang = lang;
  notify(lang === "ru" ? "Язык интерфейса: RU" : "Интерфейс тілі: KK");
}

function simulateGeneration() {
  if (generationTimer) {
    return;
  }

  let progress = 0;
  progressBar.style.width = "0%";
  progressText.textContent = "Генерация запущена...";

  generationTimer = window.setInterval(() => {
    progress += Math.floor(Math.random() * 18) + 8;
    if (progress >= 100) {
      progress = 100;
      window.clearInterval(generationTimer);
      generationTimer = null;
      progressBar.style.width = "100%";
      progressText.textContent = "Готово: добавлено 12 новых вопросов в Pipeline.";
      addDemoQuestion("ai");
      notify("AI-генерация завершена");
      return;
    }
    progressBar.style.width = `${progress}%`;
    progressText.textContent = `Выполнение: ${progress}%`;
  }, 480);
}

navButtons.forEach((button) => {
  button.addEventListener("click", () => {
    setActiveNav(button);
    setActiveView(button.dataset.viewBtn);
  });
});

langButtons.forEach((btn) => {
  btn.addEventListener("click", () => switchLanguage(btn.dataset.lang));
});

[tagFilter, classFilter, typeFilter].forEach((filter) => {
  filter.addEventListener("change", applyFilters);
});

openEditorBtn.addEventListener("click", () => openEditor());
closeEditorBtn.addEventListener("click", closeEditor);
editorModal.addEventListener("click", (event) => {
  if (event.target === editorModal) {
    closeEditor();
  }
});

addQuestionBtn.addEventListener("click", () => {
  addDemoQuestion("manual");
  notify("Добавлена демонстрационная карточка вопроса");
});

runGenerationBtn.addEventListener("click", simulateGeneration);

notifyBtn.addEventListener("click", () => {
  notify("3 новых генерации ИИ ожидают ревью");
});

questionList.addEventListener("click", (event) => {
  const card = event.target.closest(".question-card");
  if (!card) {
    return;
  }

  if (event.target.classList.contains("approve-btn")) {
    updateCardStatus(card, "published");
    notify("Вопрос опубликован");
    return;
  }

  if (event.target.classList.contains("reject-btn")) {
    updateCardStatus(card, "review");
    notify("Вопрос отправлен на доработку");
    return;
  }

  if (event.target.classList.contains("edit-btn")) {
    const ruText = card.querySelector("h3").textContent.replace("RU: ", "");
    const kkText = card.querySelector("p").textContent.replace("KK: ", "");
    openEditor(ruText, kkText);
  }
});

function updateOptionInputsType() {
  const inputType = questionTypeSelect.value === "single" ? "radio" : "checkbox";
  optionsRu.querySelectorAll("input[type='radio'], input[type='checkbox']").forEach((input) => {
    input.type = inputType;
  });
  optionsKk.querySelectorAll("input[type='radio'], input[type='checkbox']").forEach((input) => {
    input.type = inputType;
  });
}

questionTypeSelect.addEventListener("change", updateOptionInputsType);

addOptionRu.addEventListener("click", () => {
  const inputType = questionTypeSelect.value === "single" ? "radio" : "checkbox";
  optionsRu.appendChild(createOptionRow("Ru", inputType));
});

addOptionKk.addEventListener("click", () => {
  const inputType = questionTypeSelect.value === "single" ? "radio" : "checkbox";
  optionsKk.appendChild(createOptionRow("Kk", inputType));
});

[optionsRu, optionsKk].forEach((container) => {
  container.addEventListener("click", (event) => {
    if (!event.target.classList.contains("remove-option")) {
      return;
    }
    if (container.querySelectorAll(".option-row, label").length <= 2) {
      notify("Нужно минимум 2 варианта ответа");
      return;
    }
    event.target.closest("label").remove();
  });
});

copyToLectureBtn.addEventListener("click", () => {
  const text = aiExplanation.textContent.trim();
  lectureDraft.value = lectureDraft.value ? `${lectureDraft.value}\n\n${text}` : text;
  setActiveView("lectures");
  notify("Объяснение скопировано в Лекции");
});

approveFromModalBtn.addEventListener("click", () => {
  notify("Изменения сохранены и одобрены");
  closeEditor();
});

rejectFromModalBtn.addEventListener("click", () => {
  notify("Правка отклонена, требуется доработка");
  closeEditor();
});

ensureRemovers(optionsRu);
ensureRemovers(optionsKk);
setActiveView("pipeline");
switchLanguage("ru");
applyFilters();
lucide.createIcons();
