create table lectures (
    id bigint generated by default as identity primary key,
    current_version_id bigint,
    status varchar(32) not null,
    created_by bigint references app_users(id) on delete set null,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

create table lecture_versions (
    id bigint generated by default as identity primary key,
    lecture_id bigint not null references lectures(id) on delete cascade,
    version_no integer not null,
    topic_id bigint references topics(id) on delete restrict,
    title_ru varchar(255),
    title_kk varchar(255),
    content_ru_html text,
    content_kk_html text,
    source varchar(512),
    control_mode varchar(32) not null,
    checkpoint_count_requested integer not null default 0,
    published_at timestamp with time zone,
    created_at timestamp with time zone not null default now(),
    constraint uq_lecture_versions_lecture_version unique (lecture_id, version_no)
);

alter table lectures
    add constraint fk_lectures_current_version
    foreign key (current_version_id) references lecture_versions(id);

create table lecture_attachments (
    id bigint generated by default as identity primary key,
    lecture_version_id bigint not null references lecture_versions(id) on delete cascade,
    title varchar(255) not null,
    url varchar(1024) not null,
    media_type varchar(64) not null,
    sort_order integer not null default 0,
    created_at timestamp with time zone not null default now()
);

create table lecture_checkpoints (
    id bigint generated by default as identity primary key,
    lecture_version_id bigint not null references lecture_versions(id) on delete cascade,
    question_version_id bigint not null references question_versions(id) on delete restrict,
    sort_order integer not null default 0,
    selection_mode varchar(32) not null,
    created_at timestamp with time zone not null default now(),
    constraint uq_lecture_checkpoint_question unique (lecture_version_id, question_version_id)
);

create index idx_lectures_status on lectures(status);
create index idx_lectures_created_at on lectures(created_at);
create index idx_lecture_versions_lecture on lecture_versions(lecture_id);
create index idx_lecture_versions_topic on lecture_versions(topic_id);
create index idx_lecture_versions_control_mode on lecture_versions(control_mode);
create index idx_lecture_attachments_version on lecture_attachments(lecture_version_id);
create index idx_lecture_checkpoints_version on lecture_checkpoints(lecture_version_id);
create index idx_lecture_checkpoints_question on lecture_checkpoints(question_version_id);
