create table ai_generation_jobs (
    id bigint generated by default as identity primary key,
    job_type varchar(64) not null,
    status varchar(32) not null,
    provider_name varchar(64) not null,
    model_name varchar(128) not null,
    topic_id bigint not null references topics(id) on delete restrict,
    atomic_skill_id bigint references atomic_skills(id) on delete restrict,
    question_type varchar(32) not null,
    requested_count integer not null,
    difficulty integer not null,
    language_mode varchar(16) not null,
    instruction text,
    request_payload_json text not null,
    retry_count integer not null default 0,
    error_code varchar(128),
    error_message varchar(512),
    created_by bigint references app_users(id) on delete set null,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    completed_at timestamp with time zone
);

create table ai_generated_question_batches (
    id bigint generated by default as identity primary key,
    job_id bigint not null unique references ai_generation_jobs(id) on delete cascade,
    status varchar(32) not null,
    created_at timestamp with time zone not null default now()
);

create table ai_generated_question_items (
    id bigint generated by default as identity primary key,
    batch_id bigint not null references ai_generated_question_batches(id) on delete cascade,
    review_status varchar(32) not null,
    question_type varchar(32) not null,
    difficulty integer not null,
    body_ru text not null,
    body_kk text not null,
    explanation_ru text,
    explanation_kk text,
    source varchar(512) not null,
    options_json text,
    answer_key_json text not null,
    quality_score integer not null,
    quality_notes varchar(512),
    flags_json text,
    created_question_id bigint references questions(id) on delete set null,
    reviewed_by bigint references app_users(id) on delete set null,
    reviewed_at timestamp with time zone,
    created_at timestamp with time zone not null default now()
);

create index idx_ai_generation_jobs_status on ai_generation_jobs(status);
create index idx_ai_generation_jobs_topic on ai_generation_jobs(topic_id);
create index idx_ai_generated_items_batch on ai_generated_question_items(batch_id);
create index idx_ai_generated_items_review_status on ai_generated_question_items(review_status);
