create table device_tokens (
    id bigint generated by default as identity primary key,
    user_id bigint not null references app_users(id) on delete cascade,
    provider varchar(64) not null,
    platform varchar(32) not null,
    token_hash varchar(128) not null,
    enabled boolean not null default true,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    unique (provider, token_hash)
);

create table push_notifications (
    id bigint generated by default as identity primary key,
    text varchar(120) not null,
    scheduled_at_utc timestamp with time zone not null,
    target_screen varchar(64) not null,
    target_payload_json text not null,
    status varchar(32) not null,
    created_by bigint references app_users(id) on delete set null,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    sent_at timestamp with time zone,
    cancelled_at timestamp with time zone,
    failure_code varchar(128),
    failure_message varchar(512)
);

create table push_delivery_logs (
    id bigint generated by default as identity primary key,
    push_notification_id bigint not null references push_notifications(id) on delete cascade,
    provider_name varchar(64) not null,
    delivery_status varchar(32) not null,
    provider_message_id varchar(128),
    error_code varchar(128),
    error_message varchar(512),
    attempted_at timestamp with time zone not null default now()
);

create index idx_device_tokens_user on device_tokens(user_id);
create index idx_push_notifications_status on push_notifications(status);
create index idx_push_notifications_due on push_notifications(status, scheduled_at_utc);
create index idx_push_delivery_logs_notification on push_delivery_logs(push_notification_id);
