create table quiz_rooms (
    id bigint generated by default as identity primary key,
    code varchar(16) not null unique,
    host_student_profile_id bigint not null references student_profiles(id) on delete cascade,
    subject_id bigint references subjects(id) on delete set null,
    grade_id bigint references grades(id) on delete set null,
    language varchar(8) not null,
    difficulty integer,
    question_count integer not null,
    round_seconds integer not null,
    max_players integer not null,
    status varchar(32) not null,
    created_at timestamp with time zone not null default now(),
    started_at timestamp with time zone,
    finished_at timestamp with time zone
);

create table quiz_participants (
    id bigint generated by default as identity primary key,
    room_id bigint not null references quiz_rooms(id) on delete cascade,
    student_profile_id bigint not null references student_profiles(id) on delete cascade,
    display_name varchar(255) not null,
    ready boolean not null default false,
    joined_at timestamp with time zone not null default now(),
    constraint uq_quiz_participant_student unique (room_id, student_profile_id)
);

create table quiz_rounds (
    id bigint generated by default as identity primary key,
    room_id bigint not null references quiz_rooms(id) on delete cascade,
    question_version_id bigint not null references question_versions(id) on delete restrict,
    order_no integer not null,
    points numeric(6,2) not null default 1,
    constraint uq_quiz_round_order unique (room_id, order_no),
    constraint uq_quiz_round_question unique (room_id, question_version_id)
);

create table quiz_answers (
    id bigint generated by default as identity primary key,
    round_id bigint not null references quiz_rounds(id) on delete cascade,
    participant_id bigint not null references quiz_participants(id) on delete cascade,
    answer_json text not null,
    is_correct boolean not null,
    points_awarded numeric(6,2) not null,
    answered_at timestamp with time zone not null default now(),
    constraint uq_quiz_answer_round_participant unique (round_id, participant_id)
);

create table quiz_results (
    id bigint generated by default as identity primary key,
    room_id bigint not null references quiz_rooms(id) on delete cascade,
    participant_id bigint not null references quiz_participants(id) on delete cascade,
    total_questions integer not null,
    correct_answers integer not null,
    score numeric(8,2) not null,
    max_score numeric(8,2) not null,
    percent integer not null,
    created_at timestamp with time zone not null default now(),
    constraint uq_quiz_result_participant unique (room_id, participant_id)
);

create index idx_quiz_rooms_code on quiz_rooms(code);
create index idx_quiz_rooms_status on quiz_rooms(status);
create index idx_quiz_participants_room on quiz_participants(room_id);
create index idx_quiz_rounds_room on quiz_rounds(room_id);
create index idx_quiz_answers_participant on quiz_answers(participant_id);
create index idx_quiz_results_room on quiz_results(room_id);
