create table question_import_jobs (
    id bigint generated by default as identity primary key,
    status varchar(32) not null,
    source_type varchar(32) not null,
    total_rows integer not null,
    imported_rows integer not null default 0,
    error_rows integer not null default 0,
    created_at timestamp with time zone not null default now()
);

create table question_import_errors (
    id bigint generated by default as identity primary key,
    job_id bigint not null references question_import_jobs(id) on delete cascade,
    row_no integer not null,
    error_code varchar(128) not null,
    message varchar(512) not null
);

create index idx_question_import_jobs_created_at on question_import_jobs(created_at);
create index idx_question_import_errors_job on question_import_errors(job_id, row_no);
