alter table question_import_jobs
    add column original_filename varchar(255);

alter table question_import_jobs
    add column source_payload text;

create table question_flags (
    id bigint generated by default as identity primary key,
    question_id bigint not null references questions(id) on delete cascade,
    question_version_id bigint references question_versions(id) on delete set null,
    source varchar(32) not null,
    status varchar(32) not null,
    reason varchar(512) not null,
    created_at timestamp with time zone not null default now(),
    resolved_at timestamp with time zone
);

create index idx_question_flags_question_status on question_flags(question_id, status);
create index idx_question_flags_created_at on question_flags(created_at);
