alter table question_versions
    add column subject_id bigint references subjects(id) on delete restrict;

create table question_version_topics (
    id bigint generated by default as identity primary key,
    question_version_id bigint not null references question_versions(id) on delete cascade,
    topic_id bigint not null references topics(id) on delete restrict,
    is_primary boolean not null default false,
    constraint uq_question_version_topic unique (question_version_id, topic_id)
);

create table question_version_grades (
    id bigint generated by default as identity primary key,
    question_version_id bigint not null references question_versions(id) on delete cascade,
    grade_id bigint not null references grades(id) on delete restrict,
    constraint uq_question_version_grade unique (question_version_id, grade_id)
);

create index idx_qv_topics_version on question_version_topics(question_version_id);
create index idx_qv_topics_topic on question_version_topics(topic_id);
create index idx_qv_grades_version on question_version_grades(question_version_id);
create index idx_qv_grades_grade on question_version_grades(grade_id);
create index idx_question_versions_subject on question_versions(subject_id);

update question_versions qv
set subject_id = (select t.subject_id from topics t where t.id = qv.topic_id)
where qv.topic_id is not null;

insert into question_version_topics (question_version_id, topic_id, is_primary)
select id, topic_id, true
from question_versions
where topic_id is not null;

insert into question_version_grades (question_version_id, grade_id)
select qv.id, t.grade_id
from question_versions qv
join topics t on t.id = qv.topic_id
where qv.topic_id is not null;

alter table question_versions alter column subject_id set not null;
