create table subjects (
    id bigint generated by default as identity primary key,
    code varchar(64) not null unique,
    title_ru varchar(255) not null,
    title_kk varchar(255) not null,
    created_at timestamp with time zone not null default now()
);

create table grades (
    id bigint generated by default as identity primary key,
    grade_no integer not null unique,
    title_ru varchar(64) not null,
    title_kk varchar(64) not null
);

create table topics (
    id bigint generated by default as identity primary key,
    subject_id bigint not null references subjects(id),
    grade_id bigint not null references grades(id),
    parent_id bigint references topics(id),
    code varchar(128) not null,
    title_ru varchar(255) not null,
    title_kk varchar(255) not null,
    created_at timestamp with time zone not null default now(),
    unique(subject_id, grade_id, parent_id, code)
);

insert into subjects (code, title_ru, title_kk)
values
    ('math', 'Математика', 'Математика'),
    ('kazakh_language', 'Казахский язык', 'Қазақ тілі'),
    ('world_around', 'Познание мира', 'Дүниетану');

insert into grades (grade_no, title_ru, title_kk)
values
    (1, '1 класс', '1 сынып'),
    (2, '2 класс', '2 сынып'),
    (3, '3 класс', '3 сынып'),
    (4, '4 класс', '4 сынып'),
    (5, '5 класс', '5 сынып');

insert into topics (subject_id, grade_id, parent_id, code, title_ru, title_kk)
select s.id, g.id, null, 'percent-basics', 'Проценты', 'Пайыздар'
from subjects s
join grades g on g.grade_no = 4
where s.code = 'math';
