-- Timezone устройства: хранится при регистрации браузерной подписки.
-- Используется для определения местного времени пользователя при рассылке.
-- Nullable: старые подписки не имеют этого поля (умолчание: серверная тайм-зона).
alter table device_tokens add column timezone varchar(50);

-- Кампании автоматической повторяющейся рассылки push-уведомлений.
-- В отличие от разовых push_notifications (outbox), кампания — это правило расписания.
-- Каждый день при совпадении send_time + days_of_week кампания автоматически рассылается
-- всем активным подписчикам (device_tokens provider=webpush, enabled=true).
--
-- body_template поддерживает переменные: {streak} — текущая серия дней пользователя,
-- {name} — имя пользователя. Подстановка выполняется per-device при отправке.
create table push_campaigns (
    id bigint generated by default as identity primary key,
    name varchar(100) not null,
    body_template varchar(500) not null,
    target_screen varchar(64) not null,
    target_payload_json text not null default '{}',
    -- Время отправки в серверной тайм-зоне (HH:mm), хранится как time
    send_time time not null,
    -- Дни недели: ALL — каждый день, или список MON,TUE,WED,THU,FRI,SAT,SUN через запятую
    days_of_week varchar(50) not null default 'ALL',
    enabled boolean not null default true,
    -- Метка последнего запуска: используется чтобы не запускать кампанию дважды в день
    last_run_at timestamp with time zone,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

-- История запусков кампаний — основа статистики в админке.
-- Каждая запись соответствует одному срабатыванию кампании.
create table push_campaign_runs (
    id bigint generated by default as identity primary key,
    campaign_id bigint not null references push_campaigns(id) on delete cascade,
    triggered_at timestamp with time zone not null default now(),
    finished_at timestamp with time zone,
    devices_targeted int not null default 0,
    devices_sent int not null default 0,
    devices_failed int not null default 0
);

create index idx_push_campaigns_enabled_time on push_campaigns(enabled, send_time);
create index idx_push_campaign_runs_campaign on push_campaign_runs(campaign_id, triggered_at desc);
