-- Эталонные вопросы темы для few-shot AI-генерации (вариант B: полный пример с ключом ответа).
--
-- Назначение: методист хранит на теме 1..N образцовых вопросов (тело RU/KK + ключ ответа),
-- которые затем передаются в промпт генератора как примеры стиля и scope. Это НЕ вопросы банка:
-- ученику они не показываются и в банк не публикуются.
--
-- Хранение ключа ответа: одна колонка answer_key_json. Её содержимое зависит от question_type:
--   SCQ/MCQ   -> JSON-массив вариантов   (label, textRu, textKk, correct)   ~ ChoiceOptionForm
--   MATCHING  -> JSON-массив пар          (leftRu, leftKk, rightRu, rightKk) ~ MatchingPairForm
--   FILL_IN   -> JSON-массив пропусков    (placeholder, answer, matchMode, tolerance) ~ FillAnswerForm
-- Такой формат совпадает с формами вопроса банка, поэтому эталон легко и генерировать, и импортировать.
--
-- include_in_ai: мягкий выключатель. Эталон можно хранить, но временно не отправлять в генерацию.
-- internal_note: заметка методиста, в provider DTO НЕ уходит (см. TopicAiExampleService).
--
-- on delete cascade: эталоны логически принадлежат теме. Темы используют soft-delete (V24),
-- поэтому каскад срабатывает лишь при реальном hard-delete темы — это безопасная уборка «сирот».

create table topic_ai_examples (
    id bigint generated by default as identity primary key,
    topic_id bigint not null references topics(id) on delete cascade,
    question_type varchar(32) not null,
    difficulty integer not null,
    body_ru text not null,
    body_kk text not null,
    answer_key_json text not null,
    include_in_ai boolean not null default true,
    internal_note varchar(1000),
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

-- Основная выборка — «все эталоны темы»; отдельный индекс с include_in_ai ускоряет
-- подсчёт активных для промпта и для карточки покрытия в хабе.
create index idx_topic_ai_examples_topic on topic_ai_examples(topic_id);
create index idx_topic_ai_examples_include on topic_ai_examples(topic_id, include_in_ai);
