create table email_verification_tokens (
    id bigint generated by default as identity primary key,
    user_id bigint not null unique references app_users(id) on delete cascade,
    token_hash varchar(64) not null unique,
    expires_at timestamp with time zone not null,
    created_at timestamp with time zone not null
);

create index idx_email_verification_tokens_expires_at
    on email_verification_tokens (expires_at);
