alter table app_users
    add column email_verified_at timestamp with time zone;

-- Старые аккаунты не помечаем подтверждёнными задним числом: timestamp появляется только после
-- реального прохождения нового flow. Их прежний доступ продолжает определять enabled.
alter table email_verification_tokens
    add column status varchar(32) not null default 'PENDING';

alter table email_verification_tokens
    add column updated_at timestamp with time zone not null default now();

alter table email_verification_tokens
    add column activated_at timestamp with time zone;

alter table email_verification_tokens
    add column resend_available_at timestamp with time zone not null default now();

create table email_delivery_attempts (
    id bigint generated by default as identity primary key,
    verification_id bigint not null references email_verification_tokens(id) on delete cascade,
    provider varchar(32) not null,
    purpose varchar(64) not null,
    status varchar(32) not null,
    provider_result boolean,
    recipient_email varchar(320) not null,
    provider_message_id varchar(255),
    http_status integer,
    error_code varchar(64),
    error_message varchar(1000),
    attempted_at timestamp with time zone not null,
    completed_at timestamp with time zone not null
);

create index idx_email_delivery_attempts_verification_time
    on email_delivery_attempts (verification_id, attempted_at desc);

create index idx_email_delivery_attempts_provider_message
    on email_delivery_attempts (provider_message_id);
