-- Прогресс хранится отдельно для каждого ученика и лекции. Отсутствие строки означает
-- статус NOT_STARTED, поэтому существующим ученикам не требуется отдельный backfill.
create table student_lecture_progress (
    id bigint generated by default as identity primary key,
    student_profile_id bigint not null references student_profiles(id) on delete cascade,
    lecture_id bigint not null references lectures(id) on delete cascade,
    status varchar(32) not null,
    started_at timestamp with time zone not null,
    completed_at timestamp with time zone,
    checkpoint_passed_at timestamp with time zone,
    checkpoint_attempt_count integer not null default 0,
    constraint uk_student_lecture_progress unique (student_profile_id, lecture_id)
);

-- Индексы поддерживают два основных сценария: список статусов ученика и выборку
-- прогресса всех учеников по конкретной лекции.
create index idx_student_lecture_progress_student on student_lecture_progress(student_profile_id);
create index idx_student_lecture_progress_lecture on student_lecture_progress(lecture_id);
