create table roles (
    id bigint generated by default as identity primary key,
    code varchar(32) not null unique
);

create table app_users (
    id bigint generated by default as identity primary key,
    email varchar(320) not null unique,
    password_hash varchar(255) not null,
    full_name varchar(255) not null,
    phone varchar(64),
    enabled boolean not null default true,
    created_at timestamp with time zone not null default now()
);

create table user_roles (
    user_id bigint not null references app_users(id) on delete cascade,
    role_id bigint not null references roles(id) on delete cascade,
    primary key (user_id, role_id)
);

create table student_profiles (
    id bigint generated by default as identity primary key,
    user_id bigint not null unique references app_users(id) on delete cascade,
    grade_no integer,
    preferred_language varchar(8) not null default 'ru',
    created_at timestamp with time zone not null default now()
);

create table parent_profiles (
    id bigint generated by default as identity primary key,
    user_id bigint not null unique references app_users(id) on delete cascade,
    phone varchar(64),
    created_at timestamp with time zone not null default now()
);

insert into roles (code)
values ('ADMIN'), ('STUDENT'), ('PARENT');
