create table parent_link_invitations (
    id bigint generated by default as identity primary key,
    parent_profile_id bigint not null references parent_profiles(id) on delete cascade,
    student_profile_id bigint not null references student_profiles(id) on delete cascade,
    token_hash varchar(64) not null unique,
    status varchar(32) not null,
    expires_at timestamp with time zone not null,
    resend_available_at timestamp with time zone not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    confirmed_at timestamp with time zone,
    constraint uq_parent_link_invitation_pair unique (parent_profile_id, student_profile_id)
);

create index idx_parent_link_invitations_expires_at
    on parent_link_invitations (expires_at);

create table parent_link_delivery_attempts (
    id bigint generated by default as identity primary key,
    invitation_id bigint not null references parent_link_invitations(id) on delete cascade,
    status varchar(32) not null,
    recipient_email varchar(320) not null,
    provider_message_id varchar(255),
    http_status integer,
    error_code varchar(64),
    attempted_at timestamp with time zone not null,
    completed_at timestamp with time zone not null
);

create index idx_parent_link_delivery_invitation_time
    on parent_link_delivery_attempts (invitation_id, attempted_at desc);
