create table parent_student_links (
    id bigint generated by default as identity primary key,
    parent_profile_id bigint not null references parent_profiles(id) on delete cascade,
    student_profile_id bigint not null references student_profiles(id) on delete cascade,
    created_at timestamp with time zone not null default now(),
    constraint uq_parent_student_link unique (parent_profile_id, student_profile_id)
);

create table link_codes (
    id bigint generated by default as identity primary key,
    student_profile_id bigint not null references student_profiles(id) on delete cascade,
    code varchar(32) not null unique,
    expires_at timestamp with time zone not null,
    consumed_at timestamp with time zone,
    created_at timestamp with time zone not null default now()
);

create index idx_parent_student_links_parent on parent_student_links(parent_profile_id);
create index idx_link_codes_code on link_codes(code);
