alter table topics
    add column updated_at timestamp with time zone not null default now();

create table atomic_skills (
    id bigint generated by default as identity primary key,
    topic_id bigint not null references topics(id) on delete restrict,
    code varchar(128) not null,
    title_ru varchar(255) not null,
    title_kk varchar(255) not null,
    active boolean not null default true,
    created_at timestamp with time zone not null default now(),
    constraint uq_atomic_skills_topic_code unique (topic_id, code)
);

create index idx_topics_subject_grade on topics(subject_id, grade_id);
create index idx_topics_parent on topics(parent_id);
create index idx_atomic_skills_topic on atomic_skills(topic_id);

insert into topics (subject_id, grade_id, parent_id, code, title_ru, title_kk)
select root.subject_id,
       root.grade_id,
       root.id,
       'finding-percent-of-number',
       'Нахождение процента от числа',
       'Санның пайызын табу'
from topics root
where root.code = 'percent-basics'
  and not exists (
      select 1
      from topics existing
      where existing.subject_id = root.subject_id
        and existing.grade_id = root.grade_id
        and existing.parent_id = root.id
        and existing.code = 'finding-percent-of-number'
  );

insert into atomic_skills (topic_id, code, title_ru, title_kk)
select topic.id,
       'calculate-percent-value',
       'Вычислять процент от числа',
       'Санның пайызын есептеу'
from topics topic
where topic.code = 'finding-percent-of-number'
  and not exists (
      select 1
      from atomic_skills existing
      where existing.topic_id = topic.id
        and existing.code = 'calculate-percent-value'
  );
