alter table atomic_skills
    add column updated_at timestamp with time zone not null default now();

create table admin_content_audit_logs (
    id bigint generated by default as identity primary key,
    actor_email varchar(320) not null,
    action varchar(64) not null,
    entity_type varchar(64) not null,
    entity_id bigint not null,
    details varchar(1024),
    created_at timestamp with time zone not null default now()
);

create index idx_admin_content_audit_entity on admin_content_audit_logs(entity_type, entity_id);
create index idx_admin_content_audit_created_at on admin_content_audit_logs(created_at);
