create table questions (
    id bigint generated by default as identity primary key,
    current_version_id bigint,
    status varchar(32) not null,
    created_by bigint references app_users(id) on delete set null,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

create table question_versions (
    id bigint generated by default as identity primary key,
    question_id bigint not null references questions(id) on delete cascade,
    version_no integer not null,
    question_type varchar(32) not null,
    topic_id bigint not null references topics(id) on delete restrict,
    atomic_skill_id bigint references atomic_skills(id) on delete restrict,
    difficulty integer not null,
    body_ru text not null,
    body_kk text not null,
    explanation_ru text,
    explanation_kk text,
    source varchar(512) not null,
    options_json text,
    answer_key_json text not null,
    published_at timestamp with time zone,
    created_at timestamp with time zone not null default now(),
    constraint uq_question_versions_question_version unique (question_id, version_no)
);

alter table questions
    add constraint fk_questions_current_version
    foreign key (current_version_id) references question_versions(id);

create index idx_questions_status on questions(status);
create index idx_questions_created_at on questions(created_at);
create index idx_question_versions_question on question_versions(question_id);
create index idx_question_versions_topic on question_versions(topic_id);
create index idx_question_versions_skill on question_versions(atomic_skill_id);
create index idx_question_versions_type on question_versions(question_type);
