create table test_templates (
    id bigint generated by default as identity primary key,
    code varchar(64) not null unique,
    title_ru varchar(255) not null,
    title_kk varchar(255) not null,
    test_type varchar(32) not null,
    default_question_count integer not null,
    time_limit_seconds integer not null,
    active boolean not null default true,
    created_at timestamp with time zone not null default now()
);

create table test_sessions (
    id bigint generated by default as identity primary key,
    student_profile_id bigint not null references student_profiles(id) on delete cascade,
    test_type varchar(32) not null,
    status varchar(32) not null,
    subject_id bigint references subjects(id) on delete set null,
    grade_id bigint references grades(id) on delete set null,
    language varchar(8) not null,
    difficulty integer,
    started_at timestamp with time zone not null default now(),
    finished_at timestamp with time zone,
    time_limit_seconds integer not null,
    settings_json text not null default '{}'
);

create table test_session_questions (
    id bigint generated by default as identity primary key,
    session_id bigint not null references test_sessions(id) on delete cascade,
    question_version_id bigint not null references question_versions(id) on delete restrict,
    order_no integer not null,
    points numeric(6,2) not null default 1,
    constraint uq_test_session_questions_order unique (session_id, order_no),
    constraint uq_test_session_questions_version unique (session_id, question_version_id)
);

create table student_answers (
    id bigint generated by default as identity primary key,
    session_question_id bigint not null unique references test_session_questions(id) on delete cascade,
    answer_json text not null,
    answered_at timestamp with time zone not null default now()
);

create table answer_evaluations (
    id bigint generated by default as identity primary key,
    session_question_id bigint not null unique references test_session_questions(id) on delete cascade,
    is_correct boolean not null,
    points_awarded numeric(6,2) not null,
    details_json text not null,
    evaluated_at timestamp with time zone not null default now()
);

create table test_results (
    id bigint generated by default as identity primary key,
    session_id bigint not null unique references test_sessions(id) on delete cascade,
    total_questions integer not null,
    correct_answers integer not null,
    score numeric(8,2) not null,
    max_score numeric(8,2) not null,
    percent integer not null,
    created_at timestamp with time zone not null default now()
);

create index idx_test_sessions_student_status on test_sessions(student_profile_id, status);
create index idx_test_sessions_started_at on test_sessions(started_at);
create index idx_test_session_questions_session on test_session_questions(session_id);
create index idx_student_answers_answered_at on student_answers(answered_at);
create index idx_test_results_created_at on test_results(created_at);

insert into test_templates (code, title_ru, title_kk, test_type, default_question_count, time_limit_seconds)
values
    ('subject-slice', 'Предметный срез', 'Пәндік тест', 'SUBJECT', 10, 1500);

insert into questions (status, created_at, updated_at)
values ('PUBLISHED', now(), now());
insert into question_versions (
    question_id, version_no, question_type, topic_id, atomic_skill_id, difficulty,
    body_ru, body_kk, explanation_ru, explanation_kk, source, options_json, answer_key_json, published_at
)
select
    (select max(id) from questions),
    1,
    'SCQ',
    topic.id,
    skill.id,
    2,
    'Найдите 20% от 350.',
    '350 санының 20 пайызын табыңыз.',
    '20% = 0.2, 350 * 0.2 = 70.',
    '20% = 0.2, 350 * 0.2 = 70.',
    'Demo seed',
    '[{"label":"A","textRu":"60","textKk":"60"},{"label":"B","textRu":"70","textKk":"70"},{"label":"C","textRu":"75","textKk":"75"}]',
    '["B"]',
    now()
from topics topic
left join atomic_skills skill on skill.topic_id = topic.id and skill.code = 'calculate-percent-value'
where topic.code = 'finding-percent-of-number';
update questions
set current_version_id = (select max(id) from question_versions)
where id = (select max(id) from questions);

insert into questions (status, created_at, updated_at)
values ('PUBLISHED', now(), now());
insert into question_versions (
    question_id, version_no, question_type, topic_id, atomic_skill_id, difficulty,
    body_ru, body_kk, explanation_ru, explanation_kk, source, options_json, answer_key_json, published_at
)
select
    (select max(id) from questions),
    1,
    'MCQ',
    topic.id,
    skill.id,
    2,
    'Выберите верные равенства.',
    'Дұрыс теңдіктерді таңдаңыз.',
    '25% = 1/4 и 75% = 0.75.',
    '25% = 1/4 және 75% = 0.75.',
    'Demo seed',
    '[{"label":"A","textRu":"25% = 1/4","textKk":"25% = 1/4"},{"label":"B","textRu":"50% = 1/3","textKk":"50% = 1/3"},{"label":"C","textRu":"75% = 0.75","textKk":"75% = 0.75"}]',
    '["A","C"]',
    now()
from topics topic
left join atomic_skills skill on skill.topic_id = topic.id and skill.code = 'calculate-percent-value'
where topic.code = 'finding-percent-of-number';
update questions
set current_version_id = (select max(id) from question_versions)
where id = (select max(id) from questions);

insert into questions (status, created_at, updated_at)
values ('PUBLISHED', now(), now());
insert into question_versions (
    question_id, version_no, question_type, topic_id, atomic_skill_id, difficulty,
    body_ru, body_kk, explanation_ru, explanation_kk, source, options_json, answer_key_json, published_at
)
select
    (select max(id) from questions),
    1,
    'MATCHING',
    topic.id,
    skill.id,
    3,
    'Соотнесите проценты и десятичные дроби.',
    'Пайыздар мен ондық бөлшектерді сәйкестендіріңіз.',
    'Процент делится на 100: 50% = 0.5, 25% = 0.25.',
    'Пайызды 100-ге бөлеміз: 50% = 0.5, 25% = 0.25.',
    'Demo seed',
    '[{"leftRu":"50%","leftKk":"50%","rightRu":"0.5","rightKk":"0.5"},{"leftRu":"25%","leftKk":"25%","rightRu":"0.25","rightKk":"0.25"}]',
    '{"pairs":[{"left":"50%","right":"0.5"},{"left":"25%","right":"0.25"}]}',
    now()
from topics topic
left join atomic_skills skill on skill.topic_id = topic.id and skill.code = 'calculate-percent-value'
where topic.code = 'finding-percent-of-number';
update questions
set current_version_id = (select max(id) from question_versions)
where id = (select max(id) from questions);

insert into questions (status, created_at, updated_at)
values ('PUBLISHED', now(), now());
insert into question_versions (
    question_id, version_no, question_type, topic_id, atomic_skill_id, difficulty,
    body_ru, body_kk, explanation_ru, explanation_kk, source, options_json, answer_key_json, published_at
)
select
    (select max(id) from questions),
    1,
    'FILL_IN',
    topic.id,
    skill.id,
    2,
    '15% от 200 равно [[1]].',
    '200 санының 15 пайызы [[1]].',
    '15% = 0.15, 200 * 0.15 = 30.',
    '15% = 0.15, 200 * 0.15 = 30.',
    'Demo seed',
    '[]',
    '{"[[1]]":{"answer":"30","mode":"NUMERIC_TOLERANCE","tolerance":"0.01"}}',
    now()
from topics topic
left join atomic_skills skill on skill.topic_id = topic.id and skill.code = 'calculate-percent-value'
where topic.code = 'finding-percent-of-number';
update questions
set current_version_id = (select max(id) from question_versions)
where id = (select max(id) from questions);
