create table skill_mastery (
    id bigint generated by default as identity primary key,
    student_profile_id bigint not null references student_profiles(id) on delete cascade,
    topic_id bigint not null references topics(id) on delete restrict,
    atomic_skill_id bigint references atomic_skills(id) on delete restrict,
    attempts integer not null default 0,
    total_questions integer not null default 0,
    correct_answers integer not null default 0,
    mastery_percent numeric(5,2) not null default 0,
    last_attempt_at timestamp with time zone,
    updated_at timestamp with time zone not null default now()
);

create index idx_skill_mastery_student on skill_mastery(student_profile_id);
create index idx_skill_mastery_topic on skill_mastery(topic_id);
create index idx_skill_mastery_skill on skill_mastery(atomic_skill_id);
create index idx_skill_mastery_updated_at on skill_mastery(updated_at);
