alter table student_profiles
    add column lesson_reminders_enabled boolean not null default true;

alter table student_profiles
    add column weekly_parent_report_enabled boolean not null default true;

alter table student_profiles
    add column session_result_push_enabled boolean not null default false;

create table streaks (
    id bigint generated by default as identity primary key,
    student_profile_id bigint not null unique references student_profiles(id) on delete cascade,
    current_count integer not null default 0,
    longest_count integer not null default 0,
    last_activity_date date,
    updated_at timestamp with time zone not null default now()
);

create table achievements (
    id bigint generated by default as identity primary key,
    code varchar(64) not null unique,
    title_ru varchar(255) not null,
    title_kk varchar(255) not null,
    description_ru varchar(500) not null,
    description_kk varchar(500) not null,
    metric_code varchar(64) not null,
    required_value integer not null,
    active boolean not null default true,
    created_at timestamp with time zone not null default now()
);

create table student_achievements (
    id bigint generated by default as identity primary key,
    student_profile_id bigint not null references student_profiles(id) on delete cascade,
    achievement_id bigint not null references achievements(id) on delete restrict,
    earned_at timestamp with time zone not null default now(),
    constraint uq_student_achievement unique (student_profile_id, achievement_id)
);

create index idx_student_achievements_student on student_achievements(student_profile_id, earned_at desc);
create index idx_achievements_metric on achievements(metric_code, active);

insert into achievements (
    code, title_ru, title_kk, description_ru, description_kk, metric_code, required_value
)
values
    (
        'first-test-finished',
        'Первый срез',
        'Алғашқы тест',
        'Завершен первый предметный срез.',
        'Алғашқы пәндік тест аяқталды.',
        'completed_tests',
        1
    ),
    (
        'three-tests-finished',
        'Ритм тренировки',
        'Жаттығу ырғағы',
        'Завершены три предметных среза.',
        'Үш пәндік тест аяқталды.',
        'completed_tests',
        3
    ),
    (
        'five-day-streak',
        'Стабильный старт',
        'Тұрақты бастау',
        'Пять учебных дней подряд.',
        'Қатарынан бес оқу күні.',
        'current_streak',
        5
    );
